import NavBar from '@/components/navBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Cormorant, Catamaran } from 'next/font/google'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })
const cormorant = Cormorant({ subsets: ['latin'], variable: '--font-cormorant' });
const catamaran = Catamaran({ subsets: ['latin'], variable: '--font-catamaran' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}

// ${ cormorant.variable } ${ catamaran.variable } 